// import * as models from "models/Chat";

export const ADD_CHANNEL = 'ADD_CHANNEL'
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS'
export const FETCH_CHANNELS = 'FETCH_CHANNELS'
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS'
export const INPUT_CHANNEL = 'INPUT_CHANNEL'
export const SET_CHANNELS = 'SET_CHANNELS';
export const SWITCH_CHANNEL = 'SWITCH_CHANNEL'
export const SWITCH_CHANNEL_SUCCESS = 'SWITCH_CHANNEL_SUCCESS'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS'
export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const SEND_MESSAGE = 'SEND_MESSAGE';
